FROM spack-agent-builder:gcc

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        clang \
    && rm -rf /var/lib/apt/lists/* \
    && spack compiler find --scope=user
